# Generated by Django 5.1.3 on 2026-09-15 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_staffprofile_results_locked_coursestaffassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                    ("exam_officer", "Exam Officer"),
                    ("applicant", "Applicant"),
                    ("application_manager", "Application Manager"),
                    ("bursar", "Bursar"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="BursarProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(max_length=20, unique=True)),
                ("date_assigned", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bursarprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bursar Profile",
                "verbose_name_plural": "Bursar Profiles",
            },
        ),
    ]
